server:
  port: 8080

spring:
  profiles:
    default: local

  application:
    name: artconnect

  config:
    import:
      - security/application-db.yml
      - security/application-jwt.yml
      - security/application-oauth.yml