jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-in: 3600
  refresh-token-expire-in: 1209600

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 176525994307-3a193lc7db9ip07hs1296sn35b8u8hps.apps.googleusercontent.com
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
              - email

          kakao:
            client-id: 3d455d387676771824fbfed1c681a87e
            client-secret: ${KAKAO_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - account_email
              - profile_nickname
              - profile_image

          naver:
            client-id: { 네이버-클라이언트-ID }
            client-secret: { 네이버-시크릿 }
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            client-authentication-method: client_secret_post

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id
